apiVersion: v1
kind: Service
metadata:
  name: pipeline-service
spec:
  type: NodePort
  selector:
    app: pipeline-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007